"""Research Lab page (spec §28/§29): interactive ablation comparison."""
from __future__ import annotations

import pandas as pd
import streamlit as st

from core.retrieval import ablation_configs
from ui.common import get_ctx, get_workspace, header, sidebar_status

st.set_page_config(page_title="Research Lab · MIRA", page_icon="🔬", layout="wide")
sidebar_status()
ctx = get_ctx()
ws = get_workspace(ctx)

header("Research Lab",
       "Run the same query under different retrieval configurations and compare. "
       "Default weights are experimental, not optimal (§21).")

if ws.stats()["nodes"] == 0:
    st.info("No memories yet — ingest documents first.")
    st.stop()

with st.sidebar:
    st.subheader("Experiment")
    sets = st.multiselect("Ablation sets to compare", list(ablation_configs().keys()),
                          default=["full_mira", "vector_only", "graph_only", "radial_only"])
    final_k = st.slider("Memories retrieved per set", 3, 15, 8)
    st.caption("Weights in use (§21):  \n" + "  \n".join(
        f"`{k}` = {v}" for k, v in ws.config.get("retrieval_score", {}).items())
        or "weights: built-in defaults")

question = st.text_area("Query", height=70, placeholder="e.g. How does X relate to Y?")
run = st.button("Run comparison", type="primary", disabled=not question.strip())

if run and question.strip():
    qvec = ws.embeddings.encode([question])[0]
    results = {}
    progress = st.progress(0.0, "Running ablation sets…")
    for i, name in enumerate(sets):
        res = ws.retriever.retrieve(
            question, qvec, active_components=ablation_configs()[name],
            final_k=final_k) if hasattr(ws, "retriever") else None
        if res is None:
            from core.answer import AnswerPipeline  # noqa: F401  (build once)
            pipe = AnswerPipeline(ws.frame, ws.vs, ws.gs, ws.embeddings,
                                  llm=ws.llm, config=ws.config,
                                  doc_titles=ws._doc_titles())
            ws.retriever = pipe.retriever
            res = ws.retriever.retrieve(question, qvec,
                                        active_components=ablation_configs()[name],
                                        final_k=final_k)
        results[name] = res
        progress.progress((i + 1) / max(1, len(sets)))

    st.subheader("Top memories per ablation set")
    tabs = st.tabs(list(results.keys()))
    for tab, (name, res) in zip(tabs, results.items()):
        with tab:
            st.caption(f"{res.n_candidates} candidates · {res.latency_ms:.1f} ms")
            st.dataframe(pd.DataFrame([{
                "rank": i + 1, "concept": it.node.concept, "type": it.node.memory_type.value,
                "ring": it.node.ring, "sector": it.node.sector,
                "score": round(it.score, 4), "hops": len(it.path) - 1,
            } for i, it in enumerate(res.items)]),
                hide_index=True, use_container_width=True)

    # overlap analysis: does MIRA surface things component-only modes miss?
    if len(results) > 1:
        st.subheader("Overlap between sets (Jaccard on retrieved ids)")
        names = list(results)
        mat = []
        for a in names:
            row = []
            for b in names:
                sa = {it.node.id for it in results[a].items}
                sb = {it.node.id for it in results[b].items}
                j = len(sa & sb) / len(sa | sb) if sa | sb else 1.0
                row.append(round(j, 2))
            mat.append(row)
        st.dataframe(pd.DataFrame(mat, index=names, columns=names),
                     use_container_width=True)
        st.caption("If full MIRA's retrieval were identical to vector_only, the "
                   "extra components add nothing for this query — that is a real, "
                   "reportable finding, not a failure.")
else:
    st.info("Enter a query and press **Run comparison**. Nothing is generated by "
            "an LLM here — this page measures retrieval behavior only.")
